[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minimal_package"
version = "0.1.0"
description = "A minimal example package for PyPI"
readme = "README.md"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = []

[project.urls]
"Homepage" = "https://github.com/yourusername/minimal_package"
"Bug Tracker" = "https://github.com/yourusername/minimal_package/issues"

[tool.setuptools]
packages = ["minimal_package"]
